services:
  - type: web
    name: sns-downloader
    env: node
    plan: free
    buildCommand: npm install && pip install -U yt-dlp
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
